FROM confluentinc/cp-server-connect-base:6.1.2

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

USER root
COPY --chown=appuser:appuser target/components/packages/jkmart-netty-source-1.0.0.zip jkmart-netty-source-1.0.0.zip
USER appuser

RUN confluent-hub install --no-prompt ./jkmart-netty-source-1.0.0.zip
